### PR TITLE
Patch for editorView lifecycle

### PR DESCRIPTION
**Pull request by AsherJingkongChen**
[e1b6fc4] In src/core/createCodeMirror.ts, onCleanup is modified.

Fixed memory leaks caused by invalid destroy on editorView instance.

Below are profiles tested with rendering and disposing 200 times:

Original:
image

Modified:
image

### CODE REVIEW

**Comment by riccardoperra** [comment]
Thanks for the pr 😄 seems fine, I’m currently on vacation so I’ll look into it and merge the next week

**Comment by riccardoperra** [comment]
Released with [2.2.2](https://github.com/riccardoperra/solid-codemirror/releases/tag/solid-codemirror%402.2.2) 😄 thank you

**Comment by AsherJingkongChen** [comment]
dist seems to be broken. I have no idea why. I have cloned the repo and build directly instead.

**Comment by riccardoperra** [comment]
Should be ok now with 2.2.3. I had a CI script issue while automating the release

**Pull request merged**
